### ISSUE TITLE
POST /api/v1/accounts/login/ - 400 Bad Request; challenge_required

### ISSUE THREAD

**Issue by azkadev** [9xN/node-ig-framework#1]
I am trying to use your library to build a bot,

I have also clicked on my device but I tried to log in again it failed and this error appears

```bash
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

IgCheckpointError: POST /api/v1/accounts/login/ - 400 Bad Request; challenge_required
    at Request.handleResponseError (/home/hexaminate/azkadev/baru_test/node_modules/instagram-private-api/dist/core/request.js:108:24)
    at Request.send (/home/hexaminate/azkadev/baru_test/node_modules/instagram-private-api/dist/core/request.js:54:28)

Node.js v18.13.0

```

**Comment by 9xN** [comment]
that means your account is locked by instagram and you have to sign in manually and then confirm your email or do some kind of confirmation challenge then you can try running the bot again and it should work fine
